# -*- coding: utf-8 -*-
"""Chatbot on EV car.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UDJ4Ug8_TDiX06GMb8ooH7GSD4I2f4p0
"""

# Install required packages
!pip install pandas scikit-learn

import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
import re

# Load and prepare the data
df = pd.read_csv('/content/ElectricCarData_Clean.csv')

# Data preprocessing
df['Brand'] = df['Brand'].str.strip()
df['Model'] = df['Model'].str.strip()

# Create a combined text feature for similarity matching
df['combined_features'] = (
    df['Brand'] + ' ' +
    df['Model'] + ' ' +
    df['BodyStyle'] + ' ' +
    df['Segment'] + ' ' +
    df['PowerTrain'] + ' ' +
    df['PlugType']
)

# Initialize TF-IDF vectorizer
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(df['combined_features'])

class ElectricCarChatbot:
    def __init__(self, data):
        self.df = data
        self.vectorizer = vectorizer
        self.tfidf_matrix = tfidf_matrix

    def find_similar_cars(self, query, n=3):
        """Find similar cars based on text query"""
        query_vec = self.vectorizer.transform([query])
        similarities = cosine_similarity(query_vec, self.tfidf_matrix).flatten()
        similar_indices = similarities.argsort()[-n:][::-1]
        return self.df.iloc[similar_indices]

    def filter_cars(self, **filters):
        """Filter cars based on multiple criteria"""
        filtered_df = self.df.copy()

        for key, value in filters.items():
            if key in filtered_df.columns:
                if key in ['PriceEuro', 'Range_Km', 'TopSpeed_KmH', 'AccelSec']:
                    # Handle numeric filters
                    if isinstance(value, tuple) and len(value) == 2:
                        filtered_df = filtered_df[
                            (filtered_df[key] >= value[0]) &
                            (filtered_df[key] <= value[1])
                        ]
                    else:
                        filtered_df = filtered_df[filtered_df[key] <= value]
                elif key == 'Brand':
                    filtered_df = filtered_df[filtered_df[key].str.contains(value, case=False, na=False)]
                else:
                    filtered_df = filtered_df[filtered_df[key] == value]

        return filtered_df

    def get_car_stats(self):
        """Get overall statistics about the dataset"""
        stats = {
            'total_cars': len(self.df),
            'average_price': self.df['PriceEuro'].mean(),
            'average_range': self.df['Range_Km'].mean(),
            'brands': self.df['Brand'].nunique(),
            'most_expensive': self.df.loc[self.df['PriceEuro'].idxmax(), ['Brand', 'Model', 'PriceEuro']].to_dict(),
            'longest_range': self.df.loc[self.df['Range_Km'].idxmax(), ['Brand', 'Model', 'Range_Km']].to_dict(),
        }
        return stats

    def compare_cars(self, car1, car2):
        """Compare two cars"""
        car1_data = self.df[self.df['Model'].str.contains(car1, case=False, na=False)]
        car2_data = self.df[self.df['Model'].str.contains(car2, case=False, na=False)]

        if len(car1_data) == 0 or len(car2_data) == 0:
            return "One or both cars not found. Please check the model names."

        comparison_data = pd.concat([car1_data.iloc[0:1], car2_data.iloc[0:1]])
        return comparison_data[['Brand', 'Model', 'PriceEuro', 'Range_Km', 'TopSpeed_KmH', 'AccelSec', 'Efficiency_WhKm']]

    def recommend_cars(self, budget=None, min_range=None, body_style=None, brand=None):
        """Recommend cars based on user preferences"""
        recommendations = self.df.copy()

        if budget:
            recommendations = recommendations[recommendations['PriceEuro'] <= budget]
        if min_range:
            recommendations = recommendations[recommendations['Range_Km'] >= min_range]
        if body_style:
            recommendations = recommendations[recommendations['BodyStyle'].str.contains(body_style, case=False, na=False)]
        if brand:
            recommendations = recommendations[recommendations['Brand'].str.contains(brand, case=False, na=False)]

        # Sort by price (ascending) and range (descending)
        recommendations = recommendations.sort_values(['PriceEuro', 'Range_Km'], ascending=[True, False])

        return recommendations.head(5)

def process_user_input(user_input):
    """Process user input and extract key information"""
    user_input = user_input.lower()

    # Extract budget information
    budget_match = re.search(r'(\d+)\s*(k|thousand|euro|€)', user_input)
    budget = None
    if budget_match:
        budget = int(budget_match.group(1)) * 1000

    # Extract range information
    range_match = re.search(r'(\d+)\s*km', user_input)
    min_range = int(range_match.group(1)) if range_match else None

    # Extract body style
    body_styles = ['suv', 'sedan', 'hatchback', 'liftback', 'cabrio', 'pickup']
    body_style = next((style for style in body_styles if style in user_input), None)

    # Extract brand
    brands = df['Brand'].str.lower().unique()
    brand = next((b for b in brands if b in user_input), None)

    return {
        'budget': budget,
        'min_range': min_range,
        'body_style': body_style,
        'brand': brand
    }

# Initialize chatbot
chatbot = ElectricCarChatbot(df)

def electric_car_chatbot():
    print("🚗 Welcome to the Electric Car Assistant! 🚗")
    print("I can help you with:")
    print("• Finding electric cars by features")
    print("• Comparing different models")
    print("• Recommending cars based on your needs")
    print("• Showing car statistics")
    print("• Answering questions about electric vehicles")
    print("\nType 'help' for commands or 'quit' to exit.\n")

    while True:
        user_input = input("You: ").strip()

        if user_input.lower() in ['quit', 'exit', 'bye']:
            print("Thank you for using the Electric Car Assistant! Goodbye! 👋")
            break

        elif user_input.lower() == 'help':
            print("\nAvailable commands:")
            print("• 'stats' - Show overall statistics")
            print("• 'find [keyword]' - Find cars by keyword")
            print("• 'compare car1 vs car2' - Compare two cars")
            print("• 'recommend budget X range Y' - Get recommendations")
            print("• 'filter brand=X price<Y' - Filter cars")
            print("• 'show all' - Display all cars")
            print("• 'quit' - Exit the chatbot\n")

        elif user_input.lower() == 'stats':
            stats = chatbot.get_car_stats()
            print(f"\n📊 Electric Car Statistics:")
            print(f"Total cars in database: {stats['total_cars']}")
            print(f"Number of brands: {stats['brands']}")
            print(f"Average price: €{stats['average_price']:,.0f}")
            print(f"Average range: {stats['average_range']:.0f} km")
            print(f"Most expensive: {stats['most_expensive']['Brand']} {stats['most_expensive']['Model']} (€{stats['most_expensive']['PriceEuro']:,.0f})")
            print(f"Longest range: {stats['longest_range']['Brand']} {stats['longest_range']['Model']} ({stats['longest_range']['Range_Km']} km)\n")

        elif user_input.lower().startswith('find '):
            query = user_input[5:]
            similar_cars = chatbot.find_similar_cars(query)
            print(f"\n🔍 Found {len(similar_cars)} similar cars for '{query}':")
            for _, car in similar_cars.iterrows():
                print(f"• {car['Brand']} {car['Model']} - €{car['PriceEuro']:,.0f}, {car['Range_Km']}km range")
            print()

        elif ' vs ' in user_input.lower():
            cars = user_input.lower().split(' vs ')
            if len(cars) == 2:
                comparison = chatbot.compare_cars(cars[0].strip(), cars[1].strip())
                print(f"\n⚖️ Comparison:")
                print(comparison.to_string(index=False))
                print()
            else:
                print("Please specify exactly two cars to compare.\n")

        elif user_input.lower().startswith('recommend'):
            params = process_user_input(user_input)
            recommendations = chatbot.recommend_cars(
                budget=params['budget'],
                min_range=params['min_range'],
                body_style=params['body_style'],
                brand=params['brand']
            )

            print(f"\n🎯 Recommendations based on your criteria:")
            if len(recommendations) > 0:
                for _, car in recommendations.iterrows():
                    print(f"• {car['Brand']} {car['Model']} - €{car['PriceEuro']:,.0f}, {car['Range_Km']}km, {car['TopSpeed_KmH']}km/h")
            else:
                print("No cars found matching your criteria. Try adjusting your filters.")
            print()

        elif user_input.lower().startswith('filter'):
            # Simple filter parsing
            filters = {}
            if 'brand=' in user_input:
                brand_match = re.search(r'brand=(\w+)', user_input)
                if brand_match:
                    filters['Brand'] = brand_match.group(1)

            if 'price<' in user_input:
                price_match = re.search(r'price<(\d+)', user_input)
                if price_match:
                    filters['PriceEuro'] = int(price_match.group(1))

            if 'range>' in user_input:
                range_match = re.search(r'range>(\d+)', user_input)
                if range_match:
                    filters['Range_Km'] = (int(range_match.group(1)), 1000)

            filtered_cars = chatbot.filter_cars(**filters)
            print(f"\n🔍 Found {len(filtered_cars)} cars matching your filters:")
            for _, car in filtered_cars.head(10).iterrows():  # Show first 10
                print(f"• {car['Brand']} {car['Model']} - €{car['PriceEuro']:,.0f}, {car['Range_Km']}km")
            if len(filtered_cars) > 10:
                print(f"... and {len(filtered_cars) - 10} more cars")
            print()

        elif user_input.lower() == 'show all':
            print(f"\n📋 All electric cars ({len(df)} total):")
            for _, car in df.iterrows():
                print(f"• {car['Brand']} {car['Model']} - €{car['PriceEuro']:,.0f}, {car['Range_Km']}km")
            print()

        else:
            # General query processing
            params = process_user_input(user_input)
            if any([params['budget'], params['min_range'], params['body_style'], params['brand']]):
                recommendations = chatbot.recommend_cars(
                    budget=params['budget'],
                    min_range=params['min_range'],
                    body_style=params['body_style'],
                    brand=params['brand']
                )
                print(f"\n🤔 Based on your query, here are some suggestions:")
                if len(recommendations) > 0:
                    for _, car in recommendations.head(3).iterrows():
                        print(f"• {car['Brand']} {car['Model']} - €{car['PriceEuro']:,.0f}, {car['Range_Km']}km")
                else:
                    print("No specific matches found. Try being more specific or type 'help' for commands.")
                print()
            else:
                print("I'm not sure I understand. Type 'help' to see what I can do, or try asking about specific cars, budgets, or features.\n")

# Run the chatbot
electric_car_chatbot()